name: Saluside Cloud Builder

on:
  workflow_dispatch:

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Google Repo Tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo

      - name: Sync and Build Android Source
        run: |
          set -e
          echo "Текущая директория: $(pwd)"
          mkdir -p aosp
          cd aosp
          echo "Мы внутри: $(pwd)"
          
          echo "Настройка git..."
          git config --global user.name "nnoker"
          git config --global user.email "salusidemod@gmail.com"
          
          echo "Проверка доступности repo:"
          which repo || echo "repo не найдена в PATH!"
          
          echo "Инициализация репозитория..."
          python3 ~/bin/repo init -u https://github.com/LineageOS/android.git -b lineage-22.1 --depth=1 --no-repo-verify
          
          echo "Содержимое папки после init:"
          ls -la
          
          echo "Старт синхронизации..."
          python3 ~/bin/repo sync -c -j4 --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync
          
          echo "Содержимое папки после sync:"
          ls -la
          
          source build/envsetup.sh
          lunch lineage_miatoll-userdebug
          mka bacon
