name: SalusideOS Cloud Builder

on:
  workflow_dispatch:

jobs:
  build_android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Builder Config
      uses: actions/checkout@v4

    - name: Update System
      run: sudo apt-get update

    - name: Install Tools
      run: sudo apt-get install -y bc bison build-essential curl flex g++-multilib gcc-multilib git gnupg gperf zip zlib1g-dev

    - name: Install Google Repo Tool
      run: |
        mkdir -p ~/bin
        curl https://googlesource.com > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: Sync Android Source Code
      run: |
        git config --global user.name "notarealmnoker"
        git config --global user.email "saluside@example.com"
        repo init -u https://github.com -b lineage-21 --git-lfs --depth=1
        repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
