name: Saluside Cloud Builder

on:
  workflow_dispatch:

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Google Repo Tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo

      - name: Sync and Build Android Source
        run: |
          set -e
          echo "Текущая директория: $(pwd)"
          
          # Полная очистка перед скачиванием
          rm -rf aosp
          mkdir -p aosp
          cd aosp
          echo "Мы внутри: $(pwd)"
          
          echo "Настройка git..."
          git config --global user.name "nnoker"
          git config --global user.email "salusidemod@gmail.com"
          git config --global advice.detachedHead false
          
          echo "Инициализация репозитория..."
          python3 ~/bin/repo init -u https://github.com/LineageOS/android.git -b lineage-21 --depth=1 --no-repo-verify
          
          echo "Старт синхронизации..."
          python3 ~/bin/repo sync -c -j4 --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync
          
          echo "Настройка окружения для Poco F3 (alioth)..."
          source build/envsetup.sh
          lunch lineage_alioth-userdebug
          
          echo "Запуск компиляции прошивки..."
          mka bacon
